
FROM	node:16-buster-slim
RUN	mkdir -p /app
WORKDIR	/app
COPY	package.json	/app
COPY	yarn.lock	/app
RUN	yarn install
COPY	.	/app
EXPOSE	3000
ENV	DIRECTUS_URL	https://bvpk-back.linus.cx
CMD	["yarn","dev"]
